{{- if and .Values.auth.enabled .Values.auth.apiKey (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aipod.authSecretName" . }}
  labels:
    {{- include "aipod.commonLabels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.secretKey }}: {{ .Values.auth.apiKey | quote }}
{{- end }}
{{- if and .Values.model.apiKey (not .Values.model.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aipod.modelSecretName" . }}
  labels:
    {{- include "aipod.commonLabels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.model.apiKeyName }}: {{ .Values.model.apiKey | quote }}
{{- end }}
